Django/Alpsite/alp/urls.py
from django.urls import path

from . import views

app_name = "alp"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("information/", views.InformationPage.as_view(), name="information"),
    path("information/<int:pk>", views.InformationDetailPage.as_view(), name="info_detail"),
    path("gallery/", views.GalleryPage.as_view(), name="gallery"),
    path("contact/", views.ContactPage.as_view(), name="contact"),
    
] 

Django/Alpsite/alpsite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import include 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from alp import urls as alp_urls
from userprofile import urls as profile_urls
from reservation import urls as reservation_urls
from material import urls as material_urls
from application import urls as application_urls
from communication import urls as communication_urls
from django.contrib import admin
from . import views 



admin.site.site_header = 'Die Alp - Administration'
admin.site.index_title = 'Content Administration'
admin.site.site_title = 'Die Alp - Administration'


urlpatterns = [
    path("admin/", admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path("", include(alp_urls, namespace="alp")),
    path("profile/", include(profile_urls, namespace="profiles")),
    path("reservation/", include(reservation_urls, namespace="reservation")),
    path("material/", include(material_urls, namespace="material")),
    path("application/", include(application_urls, namespace="application")),
    path("communication/", include(communication_urls, namespace="communication")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/Alpsite/application/urls.py
from django.urls import path

from . import views

app_name = "application"

urlpatterns = [
    path("applicationForm", views.ApplicationFormView.as_view(), name="applicationForm"),
    path("<int:id>/", views.ApplicationAcceptanceView.as_view(), name="userinfo"),
    path("decision/<int:id>/", views.UserDecisionView.as_view(), name="decision"),
] 

Django/Alpsite/alp/models.py
from django.db import models

class Picture(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='images',null=True)
    is_gallery_picture = models.BooleanField(default=False, verbose_name="Bild für Gallery")

    def __str__(self) -> str:
        return f"{self.title}"
    
    class Meta:
        verbose_name_plural  =  "Bilder"

class Video(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    video = models.FileField(upload_to='videos',null=True)

    def __str__(self) -> str:
        return f"{self.title}"
    
    class Meta:
        verbose_name_plural  =  "Videos"

class InformationDetail(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    images = models.ManyToManyField(Picture, blank=True)
    videos = models.ManyToManyField(Video, blank=True)
    secure = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.title}"
    
    class Meta:
        verbose_name_plural  =  "Informationen"
    
class Contact(models.Model):
    name = models.CharField(max_length=60)
    phone = models.CharField(max_length=13)
    email = models.EmailField(max_length = 254)
    gives_permission = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.name}"
    
    class Meta:
        verbose_name_plural  =  "Kontakte"

Django/Alpsite/alp/views.py
from datetime import date, time, datetime, timedelta
from typing import Any, Dict
from django.utils.safestring import mark_safe
from django.urls import reverse, re_path
from django.utils import timezone
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import  ListView, TemplateView, FormView
from django.contrib import messages
from django.db.models import Q
from alpsite.decorator import you_shall_not_pass
from .models import InformationDetail, Picture, Contact

#from .models import Event, ClosedDay, Calendar, ClosedTimeWondow


class HomePage(TemplateView):
    http_method_names = ["get"]
    template_name = "alp/homepage.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)


        return context


@method_decorator(you_shall_not_pass(), name='dispatch')    
class InformationPage(TemplateView):
    http_method_names = ["get"]
    template_name = "alp/information.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        all_infos = InformationDetail.objects.all()
        
        context['all_infos'] = all_infos

        return context
    
class InformationDetailPage(TemplateView):
    http_method_names = ["get"]
    template_name = "alp/information_detail.html"

    def should_redirect(self, info_detail):
        site_should_be_secure = getattr(info_detail, 'secure')
        return site_should_be_secure and not self.request.user.is_authenticated

    def dispatch(self, *args, **kwargs):
        info_detail = InformationDetail.objects.filter(id=self.kwargs['pk']).first()

        if info_detail is None:
            return super().dispatch(*args, **kwargs)

        if self.should_redirect(info_detail):
            return HttpResponseRedirect('/login/')
        else:
            return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        info_detail = InformationDetail.objects.filter(id=self.kwargs['pk']).first()

        if info_detail is None:
            return context

        info_detail_images = info_detail.images.all()
        info_detail_videos = info_detail.videos.all()

        context['details'] = info_detail
        context['images'] = info_detail_images
        context['videos'] = info_detail_videos

        return context



        

@method_decorator(you_shall_not_pass(), name='dispatch')
class GalleryPage(TemplateView):
    http_method_names = ["get"]
    template_name = "alp/gallery.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context['images'] = Picture.objects.filter(is_gallery_picture=True)

        return context
    
@method_decorator(you_shall_not_pass(), name='dispatch')
class ContactPage(TemplateView):
    http_method_names = ["get"]
    template_name = "alp/contact.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context['contacts'] = Contact.objects.all()

        return context
    

Django/Alpsite/templates/alp/contact.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="section-contact">
    <div class="contact">
        {% for contact in contacts %}

        <div class="contact__box">
            <h3 class="heading-secondary--sub">{{contact.name}}</h3>
            <p>
                Telefon: <br />
                {{contact.phone}} <br />
                E-Mail: <br />
                {{contact.email}}
            </p>
        </div>

        {% endfor %}
    </div>
</section>
{% endblock content %}















<!-- <div class="col-md-6 mb-2">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title heading-tertiary--small">{{contact.name}}</h3>
            <p class="card-text">
                Telefon: <br />
                {{contact.phone}} <br />
                E-Mail: <br />
                {{contact.email}}
            </p>
        </div>
    </div>
</div> -->

Django/Alpsite/templates/alp/gallery.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="section-gallery">
    <h3 class="heading-tertiary">Gallery</h3>

    <div class="gallery">
        {% for image in images %}
        <!-- <div class="col-sm-5 mb-2 me-2"> -->
        <figure class="gallery__item">
            <img
                src="{{image.image.url}}"
                alt="{{image.description}}"
                class="gallery__img"
            />
            <!-- <figcaption>{{image.description}}</figcaption> -->
        </figure>
        <!-- </div> -->
        {% endfor %}
    </div>
</section>

{% endblock content %}

Django/Alpsite/templates/alp/homepage.html
{% extends "base.html" %} 
{% load static %} 

{% block content %}

    <section class="section-heading">
        <header class="header-background">
            <div class="header__heading-box">
                <h1>
                    <span class="heading-primary">Die Alp</span>
                    <span class="heading-primary--sub"
                        >eine Oase zum Wohlfühlen..</span
                    >
                </h1>
            </div>
        </header>
        {% if not request.user.is_authenticated %}
        <div class="centered-text">
            <p class="centered-text__content">
                <a href="{% url 'application:applicationForm' %}">Antrag für Login</a>
            </p>
        </div>
        {% endif %}
    </section>

{% endblock content %}

Django/Alpsite/templates/alp/information.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="section-information">
    <h2 class="heading-secondary">Herzlich Willkommen</h2>
    <span class="heading-secondary--sub">schön besuchst du unsere Hütte</span>

    <p>Hier findest du alles was du zur Nutzung der Hütte wissen musst...</p>

    <p>
        Bitte teile deinen Aufenthalt - mache einen Eintrag ins Tagebuch ☺.
    
        Damit du deinen Aufenthalt geniessen kannst, haben wir nachfolgend ein
        paar Infos für dich. 
        In der Küche hat es ein Merkblatt, auf dem die wichtigsten Punkte
        nochmals aufgeführt sind. 
        Bitte trage Sorge zur Hütte und zu den alten Fenstern (diese sind
        Chrigus Heiligtum) und 
        verlasse diese so wie du sie angetroffen hast.
    </p>
    <div class="section-link">
    <!-- <h3 class="heading-tertiary">Inhaltsverzeichnis</h3> -->
    
        <ul class="ul-link">
            {% for info in all_infos %}
            <li class="info-list-item">
                <a class="information__link" href="{% url 'alp:info_detail' info.id %}"
                    >{{info.title}}</a
                >
            </li>
            {% endfor %}
        </ul>
    </div>
</section>

{% endblock content %}

Django/Alpsite/templates/alp/information_detail.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="section-information">
    <a href="{% url 'alp:information' %}" class="button-close">
        <span class="button-close__icon">&nbsp;</span>
    </a>

    <div>
        <h3 class="heading-tertiary">{{details.title}}</h3>

        <div class="">{{details.description|safe}}</div>

        <div class="image-container">
            {% for image in images %}

            <figure class="">
                <img
                    src="{{image.image.url}}"
                    alt="{{image.description}}"
                    class=""
                    width= "90%"
                    height="90%"
                />
                <figcaption>{{image.description}}</figcaption>
            </figure>

            {% endfor %}
        </div>

        <div class="container">
            <div class="row">
                {% for video in videos %}
                <div class="col-sm mb-2 me-2">
                    <video
                        src="{{video.video.url}}"
                        controls
                        type="video/mp4"
                        class="video"
                    >
                        Your browser does not support the video
                    </video>
                    <!-- <p>{{video.description}}</p> -->
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock content %}