Django/Reitplatzplaner/Terminplaner/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import include 
from django.conf.urls.static import static 
from kalender import urls as kalender_urls
from profiles import urls as profiles_urls
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(kalender_urls, namespace="kalender")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django/Reitplatzplaner/kalender/urls.py
from django.urls import path

from . import views

app_name = "kalender"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("calendar/<int:pk>/", views.DayCalendarPage.as_view(), name="calendar"),
    path("weekcalendar/<int:pk>/", views.WeekCalendar2Page.as_view(), name="week"),
    path("hourdetail/<int:pk>/", views.OccupancyDetailPage.as_view(), name="hour"),
    
] 

Django/Reitplatzplaner/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("<int:id>/", views.ProfileDetailView.as_view(), name="detail")
    
]

Django/Reitplatzplaner/Terminplaner/templates/includes/navbar.html
<nav class="navbar sticky-top navbar-expand-md bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Reitplatzkalender</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            {% for calendar in calendars %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{calendar.name}}
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'kalender:week' calendar.id%}">Wochenkalender</a></li>
                  <li><a class="dropdown-item" href="{% url 'kalender:calendar' calendar.id %}">Tageskalender</a></li>
                </ul>
              </li>
            {% endfor %}


            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:detail' request.user.id %}">Mein Profil</a>
              </li>
                {% if request.user.is_staff or request.user.is_superuser  %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                  </li>
                {% endif %}
            {% endif %}
            </ul>
            <ul class="navbar-nav me-2 mb-2 mb-md-0">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
            {% endif %}
            </ul>
        </div>
    </div>  
</nav>
  