Django/Alpsite/alp/urls.py
from django.urls import path

from . import views

app_name = "alp"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("information/", views.InformationPage.as_view(), name="information"),
    path("information/<int:pk>", views.InformationDetailPage.as_view(), name="info_detail"),
    path("gallery/", views.GalleryPage.as_view(), name="gallery"),
    path("contact/", views.ContactPage.as_view(), name="contact"),
    
] 

Django/Alpsite/alpsite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import include 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from alp import urls as alp_urls
from userprofile import urls as profile_urls
from reservation import urls as reservation_urls
from material import urls as material_urls
from application import urls as application_urls
from communication import urls as communication_urls
from django.contrib import admin
from . import views 



admin.site.site_header = 'Die Alp - Administration'
admin.site.index_title = 'Content Administration'
admin.site.site_title = 'Die Alp - Administration'


urlpatterns = [
    path("admin/", admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path("", include(alp_urls, namespace="alp")),
    path("profile/", include(profile_urls, namespace="profiles")),
    path("reservation/", include(reservation_urls, namespace="reservation")),
    path("material/", include(material_urls, namespace="material")),
    path("application/", include(application_urls, namespace="application")),
    path("communication/", include(communication_urls, namespace="communication")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/Alpsite/material/urls.py
from django.urls import path

from . import views

app_name = "material"

urlpatterns = [
    path("", views.MaterialPage.as_view(), name="index"),
] 

Django/Alpsite/material/models.py
from django.db import models


class Item(models.Model):

    title = models.CharField(max_length=250)
    completed = models.BooleanField(default=False)

    def __str__(self) -> str:
        status = ''
        if self.completed :
            status = '(finished)'

        return f"{self.title} {status}"
    
    class Meta:
        verbose_name_plural  =  "Verbrauchsmaterial"

Django/Alpsite/material/forms.py
from django import forms

class MaterialForm(forms.Form):
    item = forms.CharField(max_length=250)

Django/Alpsite/material/views.py
from typing import Any, Dict
import json
from django.http import HttpResponse
from django.utils import timezone
from django.utils.decorators import method_decorator
from .forms import MaterialForm
from django.views.generic import  FormView
from alpsite.decorator import you_shall_not_pass
from.models import Item


@method_decorator(you_shall_not_pass(), name='dispatch')
class MaterialPage(FormView):
    form_class = MaterialForm
    template_name = "material/material.html"
    success_url = "/material/"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        item_completed = self.request.GET.get('empty', None)
        item_refilled = self.request.GET.get('refill', None)
        item_to_kill = self.request.GET.get('kill', None)

        if item_completed:
            item = Item.objects.filter(id=item_completed)
            if item:
                item[0].completed = True
                item[0].save()
        if item_refilled:
            item = Item.objects.filter(id=item_refilled)
            if item:
                item[0].completed = False
                item[0].save()
        if item_to_kill: 
            item = Item.objects.filter(id=item_to_kill)
            if item:
                item[0].delete()


        context['existing_items'] = Item.objects.filter(completed=False)
        context['empty_items'] = Item.objects.filter(completed=True)

        return context
    
    def form_valid(self, form: Any) -> HttpResponse:

        data = form.cleaned_data

        item = data['item'] 

        new_item_data = {
            'title': item,
            'completed': False
        }

        new_item = Item(**new_item_data)
        new_item.save() 

        return super().form_valid(form)
    
    def get_success_url(self) -> str:

        return super().get_success_url()

Django/Alpsite/templates/material/material.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="section-material">
        <h3 class="heading-tertiary">Verbrauchsmaterial & ToDo's</h3>
        <p>Die Liste ist zur Kommunikation gedacht.<br>
             Nutzt sie und teilt mit was vorhanden ist oder fehlt</p>

        <div class="ms-4 mt-3 mb-3">
            <form method="post">
                {% csrf_token %}
                {% for field in form%}
                    {{ field }}
                {% endfor %}
                <button type="submit" class="btn btn-outline-secondary ms-1">
                    <i class='bx bx-list-plus' ></i>
                </button>  
            </form>
        </div>

        {% if existing_items %}
        <h5 class="ms-4">Vorhanden</h5>
        <ul class="item_list">
            {% for item in existing_items %}
                <li>
                    <div class="my-1">
                        <span class="{% if item.completed %} item_completed {% endif %} item_item ms-3">
                            {{item.title}}
                        </span> 
                        {% if request.user.is_staff or request.user.is_superuser %}
                        <a href="{% url 'material:index'%}?kill={{item.id}}" class="btn btn-outline-danger btn-sm ms-2">
                            <i class='bx bx-x-circle'></i>
                        </a>
                        {% endif %}

                        <a href="{% url 'material:index'%}?empty={{item.id}}" class="btn btn-outline-warning btn-sm ms-2">
                            <i class='bx bx-minus-circle' ></i>
                        </a>                       
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% endif %}
        {% if empty_items %}
        <h5 class="ms-4">Aktuell nicht vorhanden</h5>
        <ul class="item_list">
            {% for item in empty_items %}
                <li>
                    <div class="my-1">
                        <span class="{% if item.completed %} item_completed {% endif %} item_item ms-3">
                            {{item.title}}
                        </span> 
                        {% if request.user.is_staff or request.user.is_superuser %}
                        <a href="{% url 'material:index'%}?kill={{item.id}}" class="btn btn-outline-danger btn-sm ms-2">
                            <i class='bx bx-x-circle'></i>
                        </a>
                        {% endif %}
                        
                        <a href="{% url 'material:index'%}?refill={{item.id}}" class="btn btn-outline-success btn-sm ms-2">
                            <i class='bx bx-plus-circle' ></i>
                        </a>                        
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

{% endblock content %}