Django/Reitplatzplaner/Terminplaner/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import include 
from django.conf.urls.static import static 
from kalender import urls as kalender_urls
from profiles import urls as profiles_urls
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(kalender_urls, namespace="kalender")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django/Reitplatzplaner/kalender/urls.py
from django.urls import path

from . import views

app_name = "kalender"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("calendar/<int:pk>/", views.DayCalendarPage.as_view(), name="calendar"),
    path("weekcalendar/<int:pk>/", views.WeekCalendar2Page.as_view(), name="week"),
    path("hourdetail/<int:pk>/", views.OccupancyDetailPage.as_view(), name="hour"),
    
] 

Django/Reitplatzplaner/kalender/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

EVENT_DECLARATIONS = (
    ('Training', 'Training'),
    ('Reitstunde', 'Reitstunde'),
)

class Event(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(
        User,
        on_delete= models.CASCADE,
    )
    calendar = models.ForeignKey('Calendar', on_delete=models.CASCADE, default=1)
    use_type = models.CharField(max_length=50, choices=EVENT_DECLARATIONS, default='Training')

    def __str__(self) -> str:
        return f"Im {self.calendar.name} für {self.user.username} von {self.start_time} bis {self.end_time} wegen {self.use_type}"
    
class ClosedTimeWindow(models.Model):
    start_time = models.DateTimeField(default=now)
    end_time = models.DateTimeField(default=now) 
    reason = models.TextField()
    calendar = models.ForeignKey('Calendar', on_delete=models.CASCADE, default=1)

    def __str__(self) -> str:
        return f"{self.calendar.name} gesperrt am {self.start_time} wegen {self.reason}"


class ClosedDay(models.Model):
    datum = models.DateField()
    reason = models.TextField()
    calendar = models.ForeignKey('Calendar', on_delete=models.CASCADE, default=1)

    def __str__(self) -> str:
        return f"{self.calendar.name} gesperrt am {self.datum} wegen {self.reason}"
    
class Calendar(models.Model):
    name = models.TextField()
    open_from = models.TimeField()
    open_till = models.TimeField()
    persons_per_slot = models.IntegerField()
    color_json = models.JSONField(default=dict)

    def __str__(self) -> str:
        return f"{self.name}"
    
class Rule(models.Model):
    text = models.TextField()

    def __str__(self) -> str:
        return f"{self.text[0:30]}"

Django/Reitplatzplaner/kalender/forms.py
from django import forms
from .models import EVENT_DECLARATIONS

class WeekReservationForm(forms.Form):
    event_date_start = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'id' : 'datum',
                'style' : 'margin-right : 15px;'
            }
        ))
    event_time_start = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                'type': 'time',
                'id' : 'zeit',
                'style' : 'margin-right : 15px;'
            }
    ))

class DayReservationForm(forms.Form):
    event_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'id' : 'datum',
                'style' : 'margin-right : 15px;'
            }
        ))
    event_time_start = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                'type': 'time',
                'id' : 'zeit',
                'style' : 'margin-right : 15px;'
            }
    ))
    event_time_end = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                'type': 'time',
                'id' : 'zeit',
                'style' : 'margin-right : 15px;'
            }
    ))
    use_type = forms.CharField(
        widget=forms.Select(choices=EVENT_DECLARATIONS)
    )

Django/Reitplatzplaner/kalender/views.py
import calendar
from datetime import date, time, datetime, timedelta
from typing import Any, Dict
from django.utils.safestring import mark_safe
from django.http import HttpResponseRedirect,  HttpResponse
from django.urls import reverse, re_path
from django.utils import timezone
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import  ListView, TemplateView, FormView
from django.contrib import messages
from django.db.models import Q
from .forms import WeekReservationForm, DayReservationForm
from .models import Event, ClosedDay, Calendar, ClosedTimeWindow, Rule
from Terminplaner.decorator import authenticated_user, no_further_details


class HomePage(TemplateView):
    http_method_names = ["get"]
    template_name = "kalender/homepage.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['calendars'] = Calendar.objects.all()
        rules = Rule.objects.all()
        context['rules'] = rules

        return context


############################################################################
# Day

@method_decorator(authenticated_user(), name='dispatch')
class DayCalendarPage(FormView):
    form_class = DayReservationForm
    template_name = "kalender/daycalendar.html"

    #Aktuell noch hart codierter Pfad
    def get_success_url(self):
        pk = self.kwargs['pk']
        selected_date = self.request.GET.get('selectedDate')
        success_url = f'/calendar/{pk}/'
        if selected_date:
            success_url += f'?selectedDate={selected_date}'
        return success_url

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def get_initial(self) -> Dict[str, Any]:
        initial = super().get_initial()
        selected_date = self.request.GET.get('selectedDate')
        print(selected_date)
        initial_data = {}
        if selected_date:
            initial_data['event_date'] = selected_date
        else:
            today = datetime.now()
            initial_data['event_date'] = today.strftime('%Y-%m-%d')
        initial.update(initial_data)
        return initial

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['calendars'] = Calendar.objects.all()
        
        # Datetime's für die Navigation im Kalender erstellen
        str_query_date = self.request.GET.get('selectedDate', None)

        if str_query_date:
            try:
                query_date = datetime.strptime(str_query_date, '%Y-%m-%d').date()
            except ValueError:
                query_date = None
        else:
            query_date = datetime.today()
        

        prev_date = query_date - timedelta(days=1) 
        next_date = query_date + timedelta(days=1) 
        
        
        context['selected_date'] = date(query_date.year, query_date.month, query_date.day)
        context['previous_date'] = prev_date.strftime('%Y-%m-%d')
        context['next_date'] = next_date.strftime('%Y-%m-%d')

        # Kalender-Info (Zeiten und Buchungen des angezeigten Tages erstellen)
        current_calendar = Calendar.objects.get(id=self.kwargs['pk'])
        context["current_calendar"] = current_calendar

        occupancy_colors = current_calendar.color_json
        closed_color = occupancy_colors[str(len(occupancy_colors)-1)]

        start_of_day = timezone.make_aware(datetime(query_date.year, query_date.month, query_date.day, current_calendar.open_from.hour, current_calendar.open_from.minute, 0))
        end_of_day = timezone.make_aware(datetime(query_date.year, query_date.month, query_date.day, current_calendar.open_till.hour, current_calendar.open_till.minute, 0))

        interval = []  
        current_time = start_of_day
        while current_time < end_of_day:
            interval.append(current_time)
            current_time += timedelta(minutes=15)
        
        query_blocked_date = date(year=query_date.year, month=query_date.month, day=query_date.day)
        closed_day = ClosedDay.objects.filter(datum=query_blocked_date, calendar=current_calendar)

        if closed_day:
            day_info = []
            for index, item in enumerate(interval):
                day_info.append({
                    "interval" : item,
                    "number_of_Events" : 0,
                    "occupancy_colors" : closed_color,
                })

            context['calendar_infos'] = day_info
            context['closing_reason'] = closed_day[0].reason
            
        else:
            
            closed_time_window_queryset = ClosedTimeWindow.objects.filter(calendar=current_calendar,
                                                    start_time__year = query_date.year,
                                                    start_time__month = query_date.month,
                                                    start_time__day = query_date.day)
            
            events_queryset = Event.objects.filter(calendar=current_calendar,
                                                    start_time__year = query_date.year,
                                                    start_time__month = query_date.month,
                                                    start_time__day = query_date.day)
            
            day_info = []
            for index, item in enumerate(interval):

                start = item 
                end = item + timedelta(minutes=14)

                st_starts_whitin = Q(start_time__gte=start, start_time__lte=end)
                et_ends_whitin = Q(end_time__gte=start, end_time__lte=end)
                encapsulate = Q(start_time__lte=start, end_time__gte=end)

                closed_time_window = closed_time_window_queryset.filter(st_starts_whitin | et_ends_whitin | encapsulate)

                if bool(closed_time_window):

                    day_info.append({
                        "interval" : item,
                        "occupancy_colors" : closed_color,
                        "closed_time_window_reason" : closed_time_window[0].reason
                    })

                else:
                    
                    number_of_Events = events_queryset.filter(st_starts_whitin | et_ends_whitin | encapsulate).count()

                    day_info.append({
                        "interval" : item,
                        "number_of_Events" : number_of_Events,
                        "occupancy_colors" : occupancy_colors[str(number_of_Events)]
                    })

            context['calendar_infos'] = day_info
        
        return context


    def form_valid(self, form: Any) -> HttpResponse:
        data = form.cleaned_data
        current_calendar = Calendar.objects.get(id=self.kwargs['pk'])

        open_from = current_calendar.open_from
        open_till = current_calendar.open_till


        if data['event_time_start'] >= open_from and data['event_time_start'] <= open_till:
            start_time = timezone.make_aware(data['event_time_start']) 
            end_time = timezone.make_aware(data['event_time_end'])

            event_start_Tsp = datetime.combine(data['event_date'], start_time)
            event_end_Tsp = datetime.combine(data['event_date'], end_time)

            if start_time >= end_time or data['event_date'] < date.today() :
                messages.add_message(self.request, messages.WARNING, 'Bitte gib dir Mühe bei der Eingabe')
            else:
                user = self.request.user
                calendar = current_calendar
                use_type = data['use_type']
                new_event_data = {
                    'start_time' : event_start_Tsp,
                    'end_time' : event_end_Tsp,
                    'user' : user,
                    'calendar' : calendar,
                    'use_type' : use_type
                }

                if events_of_user_check(new_event_data):
                    messages.add_message(self.request, messages.WARNING, 'Du hast zu dieser Zeit bereits eine Reservation')
                elif vacancy_check(new_event_data, current_calendar):
                    messages.add_message(self.request, messages.WARNING, 'Keine weiteren Reservationen mehr möglich')
                elif closed_time_window_check(new_event_data, current_calendar):
                    messages.add_message(self.request, messages.WARNING, 'Zu dieser Zeit kann keine Reservation gemacht werden')
                elif closed_day_check(new_event_data, current_calendar):
                    messages.add_message(self.request, messages.WARNING, 'An diesem Tag kann keine Reservation gemacht werden')
                else: 
                    new_event = Event(**new_event_data)
                    new_event.save()  
                    messages.add_message(self.request, messages.SUCCESS, 'Zeitfenster reserviert')
        else:
            messages.add_message(self.request, messages.WARNING, 'Zu dieser Zeit kann keine Reservation gemacht werden')

        return super().form_valid(form)

def events_of_user_check(event_data):

    start = event_data['start_time']
    end = event_data['end_time']

    user_events = Event.objects.filter(user__username = event_data['user'].username,
                                    calendar = event_data['calendar'],
                                    start_time__year = event_data['start_time'].year,
                                    start_time__month = event_data['start_time'].month,
                                    start_time__day = event_data['start_time'].day)
    
    st_starts_whitin = Q(start_time__gte=start, start_time__lte=end)
    et_ends_whitin = Q(end_time__gte=start, end_time__lte=end)
    swallows = Q(start_time__gte=start, end_time__lte=end)

Django/Reitplatzplaner/kalender/templates/includes/cal_day.html
{% load static %}

<section id="calendar">
    {% if messages %}
        {% for message in messages %}
            <div class="bg-{% if message.tags %}{{ message.tags }}{% endif %} bg-gradient text-center text-white py-4">{{ message }}</div>  
        {% endfor %}
    {% endif %}
    <div class="card">
        <div class="card-header day-header bg-contrast-color">
            <span class="d-flex justify-content-between">
                <a class="btn btn-outline-secondary my-2 me-1 bg-contrast-color" href="{% url 'kalender:calendar' current_calendar.id %}?selectedDate={{ previous_date }}" > <i class='bx bx-left-arrow-alt' ></i> </a>
                <h4 class="primary-color">{{current_calendar.name}}</h4>
                <a class="btn btn-outline-secondary my-2 bg-contrast-color" href="{% url 'kalender:calendar' current_calendar.id %}?selectedDate={{ next_date }}" > <i class='bx bx-right-arrow-alt'></i> </a> 
                </span>
                <form class="me-1">
                    <input type="date" id="datepicker" name="selectedDate" value="{{ selected_date|date:'Y-m-d' }}">
                    <input type="submit" value="Tag wechseln">
                </form>
                {% if closing_reason %}
                <h4>{{closing_reason}}</h4>
                {%endif%}
        </div>
        <ul class="list-group list-group-flush">

        {% for item in calendar_infos %}
            <li class="list-group-item d-flex justify-content-center" style="background-color: {{item.occupancy_colors}};">
                <div>
                    {{item.interval|time:"H:i"}}
                </div>    
            </li>   
        {% endfor %}
        </ul>
      </div>
</section>

Django/Reitplatzplaner/kalender/templates/includes/cal_input_form_sticky_footer.html
<nav class="navbar sticky-bottom navbar-expand-sm bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid d-flex justify-content-end">
        <form method="POST" enctype="multipart/form-data" class="d-flex" role="reservation">
            {% csrf_token %}

            <div class="row">
                <div class="row">
                    <div class="col-12 mb-2 d-flex justify-content-end">
                        {{form.use_type}}
                    </div>
                </div>
                <div class="col-12 mb-2 d-flex justify-content-end">
                    <label for="{{ form.event_date.id_for_label }}" style="color: white; margin-right: 15px;">Datum:</label>
                    {{ form.event_date }}
                </div>
				<div class="col-12 d-flex justify-content-end">
                    <label for="{{ form.event_time_start.id_for_label }}" style="color: white; margin-right: 15px;">Von:</label>
                    {{ form.event_time_start }}
                    <label for="{{ form.event_time_end.id_for_label }}" style="color: white; margin-right: 15px;">Bis:</label>
                    {{ form.event_time_end }}
                </div>
            </div>
            <div class="row">
				<div class="col-12">
					<button class="btn btn-outline-success mt-2" type="submit">Reservieren</button>
				</div>
            </div>
            
        </form>
    </div>
</nav>

Django/Reitplatzplaner/kalender/templates/includes/cal_week2.html
<section id="calendar">
    {% if messages %}
        {% for message in messages %}
            <div class="bg-{% if message.tags %}{{ message.tags }}{% endif %} bg-gradient text-center text-white py-4">{{ message }}</div>  
        {% endfor %}
    {% endif %}
        <div>
            <span class="d-flex justify-content-between">
                <a class="btn btn-outline-secondary my-2 me-1 bg-contrast-color" href="{% url 'kalender:week' current_calendar.id %}?selectedDate={{ previous_date }}"> <i class='bx bx-left-arrow-alt' ></i> </a>
                <div style="text-align: center;">
                    <h4>{{current_calendar.name}}</h4> 
                    {{ selected_date|date:"F Y" }}
                </div> 
                <a class="btn btn-outline-secondary my-2 bg-contrast-color" href="{% url 'kalender:week' current_calendar.id %}?selectedDate={{ next_date }}" > <i class='bx bx-right-arrow-alt'></i> </a> 
            </span>
        </div>
    
        <div class="container-fluid">
            <div class="row row-cols-7">
                
                {% for key, value in calendar_infos.items %}  
                    <div class="col">
                        <div class="card my-1 mx-1">
                            <div class="card-header day-header bg-contrast-color" >
                                <a class="link-hide" href="{% url 'kalender:calendar' current_calendar.id %}?selectedDate={{value.date|date:'Y-m-d'}}" >
                                    <div class="card-title" >
                                        <p class="mb-1">{{ value.date|date:"l" }}</p>
                                        {{ value.date|date:"d.m.y" }}
                                    </div>
                                </a>
                            </div>
                            <ul class="list-group list-group-flush">
                                {% for infos in value.day_infos%}
                                    <li class="list-group-item d-flex justify-content-center" style="background-color: {{ infos.occupancy_colors}}">
                                        <a href="{% url 'kalender:hour' current_calendar.id %}?date={{value.date|date:'Y-m-d'}}&time={{infos.interval|time:'H'}}" style="text-decoration: none; color: black;">
                                            <div>
                                                {{infos.interval|time:"H:i"}}
                                            </div>
                                        </a>    
                                    </li>    
                                {% endfor%} 
                            </ul>
                        </div>
                    </div>    
                {% endfor%}
                    
            </div>    
        </div>
    
            

</section>